--require "user.options"
--require "user.keymaps"
--require "user.plugins"
--require "user.colorscheme"
--require "user.cmp"
--require "user.lsp"
--require "user.telescope"
--require "user.gitsigns"
--require "user.treesitter"
--require "user.autopairs"
--require "user.comment"
--require "user.nvim-tree"
--require "user.bufferline"
--require "user.lualine"
--require "user.toggleterm"
--require "user.project"
--require "user.impatient"
--require "user.indentline"
--require "user.alpha"
--require "user.whichkey"
--require "user.autocommands"
--require "user.gps"
--require "user.winbar"
--require "user.lint"
--require "user.highlight"
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
-- 开启 Neovim 内置的加载缓存优化（替代 impatient.nvim）
if vim.loader then
  vim.loader.enable()
end

require "config.lazy"
require "config.nvim-tree"
require "config.telescope"
require "config.keymaps"
require "config.options"
require "config.colorscheme"
require "config.bufferline"
require("ibl").setup()
require "config.highlight"
require "config.lualine"
require "config.autopairs"
require "config.toggleterm"
-- require "config.lint"
