return {
    "folke/which-key.nvim",
    tag = "v3.17.0",
    event = "VeryLazy",
    opts = {
        -- your configuration comes here
        -- or leave it empty to use the default settings
        win = {
            border = "rounded", -- 或者 "single", "double" 等
        },
        triggers = {
            { "<leader>", mode = { "n", "v" } },
            -- { "g", mode = { "n", "v" } },
        },
        spec = {
            {"<leader>b", "<cmd>lua require('telescope.builtin').buffers(require('telescope.themes').get_dropdown{previewer = false})<cr>", desc = "Buffers" },
            { "<leader>e", "<cmd>NvimTreeToggle<cr>", desc = "Explorer" },
            { "<leader>c", "<cmd>Bdelete!<CR>", desc = "Close Buffer" },
            { "<leader>h", "<cmd>nohlsearch<CR>", desc = "No Highlight" },
            { "<leader>f", "<cmd>lua require('telescope.builtin').find_files(require('telescope.themes').get_dropdown{previewer = false})<cr>", desc = "Find files" },
            { "<leader>F", "<cmd>Telescope live_grep_args theme=ivy<cr>", desc = "Find Text" },
            { "<leader>g", group = "Git"},
            { "<leader>gg", "<cmd>lua _LAZYGIT_TOGGLE()<CR>", desc = "Lazygit" },
            { "<leader>gj", "<cmd>lua require 'gitsigns'.next_hunk()<cr>", desc = "Next Hunk" },
            { "<leader>gk", "<cmd>lua require 'gitsigns'.prev_hunk()<cr>", desc = "Prev Hunk" },
            { "<leader>gl", "<cmd>lua require 'gitsigns'.blame_line()<cr>", desc = "Blame" },
            { "<leader>gp", "<cmd>lua require 'gitsigns'.preview_hunk()<cr>", desc = "Preview Hunk" },
            { "<leader>gr", "<cmd>lua require 'gitsigns'.reset_hunk()<cr>", desc = "Reset Hunk" },
            { "<leader>gR", "<cmd>lua require 'gitsigns'.reset_buffer()<cr>", desc = "Reset Buffer" },
            { "<leader>gs", "<cmd>lua require 'gitsigns'.stage_hunk()<cr>", desc = "Stage Hunk" },
            { "<leader>gu", "<cmd>lua require 'gitsigns'.undo_stage_hunk()<cr>", desc = "Undo Stage Hunk" },
            { "<leader>go", "<cmd>Telescope git_status<cr>", desc = "Open changed file" },
            { "<leader>gb", "<cmd>Telescope git_branches<cr>", desc = "Checkout branch" },
            { "<leader>gc", "<cmd>Telescope git_commits<cr>", desc = "Checkout commit" },
            { "<leader>gd", "<cmd>Gitsigns diffthis HEAD<cr>", desc = "Diff" },
            { "<leader>l", group = "LSP"},
            { "<leader>la", "<cmd>lua vim.lsp.buf.code_action()<cr>", desc = "Code Action" },
            { "<leader>lc", "<cmd>lua require('telescope.builtin').lsp_incoming_calls()<cr>", desc = "Incoming Calls"},
            { "<leader>ld", "<cmd>Telescope diagnostics bufnr=0<cr>", desc = "Document Diagnostics" },
            { "<leader>lw", "<cmd>Telescope diagnostics<cr>", desc = "Workspace Diagnostics" },
            { "<leader>lf", "<cmd>lua vim.lsp.buf.format{async=true}<cr>", desc = "Format" },
            { "<leader>li", "<cmd>LspInfo<cr>", desc = "Info" },
            { "<leader>lI", "<cmd>LspInstallInfo<cr>", desc = "Installer Info" },
            { "<leader>lj", "<cmd>lua vim.lsp.diagnostic.goto_next()<CR>", desc = "Next Diagnostic" },
            { "<leader>lk", "<cmd>lua vim.lsp.diagnostic.goto_prev()<cr>", desc = "Prev Diagnostic" },
            { "<leader>ll", "<cmd>lua vim.lsp.codelens.run()<cr>", desc = "CodeLens Action" },
            { "<leader>lq", "<cmd>lua vim.diagnostic.setloclist()<cr>", desc = "Quickfix" },
            { "<leader>lr", "<cmd>lua vim.lsp.buf.rename()<cr>", desc = "Rename" },
            { "<leader>ls", "<cmd>lua require('telescope.builtin').lsp_document_symbols({symbol_width=60})<cr>", desc = "Document Symbols" },
            { "<leader>lS", "<cmd>lua require('telescope.builtin').lsp_dynamic_workspace_symbols({symbol_width=60})<cr>", desc = "Workspace Symbols" },
            { "<leader>n", group = "NvimTree"},
            {"<leader>nr", "<cmd>NvimTreeResize 50<cr>", desc = "Resize"},
            {"<leader>nf", "<cmd>NvimTreeFindFile<cr>", desc = "Find Current File"},
            { "<leader>s", group = "Search"},
            { "<leader>ss", "<cmd>lua require(\"telescope\").extensions.live_grep_args.live_grep_args({default_text=vim.fn.expand(\"<cword>\")})<cr>", desc = "Current String"},
            { "<leader>sb", "<cmd>Telescope git_branches<cr>", desc = "Checkout branch" },
            { "<leader>sc", "<cmd>Telescope colorscheme<cr>", desc = "Colorscheme" },
            { "<leader>sh", "<cmd>Telescope help_tags<cr>", desc = "Find Help" },
            { "<leader>sM", "<cmd>Telescope man_pages<cr>", desc = "Man Pages" },
            { "<leader>sr", "<cmd>Telescope oldfiles<cr>", desc = "Open Recent File" },
            { "<leader>sR", "<cmd>Telescope registers<cr>", desc = "Registers" },
            { "<leader>sk", "<cmd>Telescope keymaps<cr>", desc = "Keymaps" },
            { "<leader>sC", "<cmd>Telescope commands<cr>", desc = "Commands" },
            { "<leader>t", group = "Terminal"},
            { "<leader>tn", "<cmd>lua _NODE_TOGGLE()<cr>", desc = "Node" },
            { "<leader>tu", "<cmd>lua _NCDU_TOGGLE()<cr>", desc = "NCDU" },
            { "<leader>tt", "<cmd>lua _HTOP_TOGGLE()<cr>", desc = "Htop" },
            { "<leader>tp", "<cmd>lua _PYTHON_TOGGLE()<cr>", desc = "Python" },
            { "<leader>tf", "<cmd>ToggleTerm direction=float<cr>", desc = "Float" },
            { "<leader>th", "<cmd>ToggleTerm size=10 direction=horizontal<cr>", desc = "Horizontal" },
            { "<leader>tv", "<cmd>ToggleTerm size=80 direction=vertical<cr>", desc = "Vertical" },
        },
    },
    keys = {
        {
            "<leader>?",
            function()
                require("which-key").show({ global = false })
            end,
            desc = "Buffer Local Keymaps (which-key)",
        },
    },
}
